package com.pradeep.journeytracker.model;

public enum Event {
    PHONE_PE_APP_OPENED,
    USER_REGISTRATION_COMPLETE,
    USER_OPENED_RECHARGE_PAGE,
    USER_SELECTING_OPERATOR,
    USER_SELECTING_PLAN,
    USER_MADE_PAYMENT
}
